service: bluesky-api # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-1
  apiKeys:
    - bluesky_api_key
functions:
  get:
    handler: index.get
    events:
      - http:
          path: get
          method: get
    memorySize: 32
  put:
    handler: index.put
    events:
      - http:
          path: put
          method: put
          private: true
    memorySize: 128
