service: bluesky-api # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-1
  apiKeys:
    - bluesky_api_key
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/bluesky_pmdata
functions:
  get:
    handler: index.get
    events:
      - http:
          path: get/{device_id}/interval/{from}/{to}
          method: get
          request:
            parameters:
              paths:
                device_id: true
                from: true
                to: true
    memorySize: 128
  put:
    handler: index.put
    events:
      - http:
          path: put
          method: put
          private: true
    memorySize: 128
resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bluesky_pmdata
        AttributeDefinitions:
          - AttributeName: device_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: device_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
