service: bluesky-api # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-1
functions:
  ping:
    handler: index.ping
    events:
      - http:
          path: ping
          method: get
